CREATE TABLE Diagnosis (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    Name VARCHAR(50)
);

CREATE TABLE Wards (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    Name VARCHAR(50),
    MaxCount INTEGER
);

CREATE TABLE People (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    FirstName VARCHAR(20),
    LastName VARCHAR(20),
    MiddleName VARCHAR(20),
    DiagnosisID INTEGER,
    WardID INTEGER,
    FOREIGN KEY (DiagnosisID) REFERENCES Diagnosis(ID),
    FOREIGN KEY (WardID) REFERENCES Wards(ID)
);
