-- CREATE SCHEMA HOSPITAL

CREATE TABLE Diagnosis
(
    ID   SERIAL NOT NULL PRIMARY KEY UNIQUE,
    Name VARCHAR(50)
);

CREATE TABLE Wards
(
    ID       SERIAL NOT NULL PRIMARY KEY UNIQUE,
    Name     VARCHAR(50),
    MaxCount INTEGER
);

CREATE TABLE People
(
    ID          SERIAL NOT NULL PRIMARY KEY UNIQUE,
    FirstName   VARCHAR(20),
    LastName    VARCHAR(20),
    MiddleName  VARCHAR(20),
    DiagnosisID INTEGER,
    WardID      INTEGER,
    FOREIGN KEY (DiagnosisID) REFERENCES Diagnosis (ID),
    FOREIGN KEY (WardID) REFERENCES Wards (ID)
);
